### ISSUE TITLE
感谢为汉化版CyberChef做出贡献，鄙人正在做一个基于CyberChef项目打造的程序员专用工具箱

### ISSUE THREAD

**Issue by work7z** [Z2549/CyberChef_Chinese#2]
并非打广告，因为在翻阅CyberChef Issues区想了解各类现有的问题时，发现了大佬CyberChef_Chinese这个项目。 

其实我最近已经在做一个项目是https://github.com/work7z/LafTools

将会提供类似CyberChef但更加操作流程体验的数据抽取转换工具箱（不知道这样的名称是否合理贴切）

距离我第一个release还需要比较久的时间，但是我对中文版的CyberChef+AI Robot+Translation很有信心，如果各位感兴趣的话，等后面release稳定之后，欢迎提出任何建议或者想法，感谢！

在线预览版：https://cloud.laf-tools.com

**Comment by Z2549** [comment]
项目很不错，继续加油，等你第一版release

**Comment by work7z** [comment]
感谢支持！我会努力的，感谢star!

(btw, 项目全部离线功能将完全开源免费)
